on:
  push:
defaults:
  run:
    shell: bash

jobs:
  react-native:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - run: |
            java --version
            node --version
            npm --version
            docker
      - name: build
        run: |
            cd android
            chmod +x gradlew
            ./gradlew build
